import { v4 as uuidv4 } from 'uuid';
require('dotenv').config();
export default {
    async up(queryInterface) {
        return queryInterface.bulkInsert('song', [
            {
                id: uuidv4(),
                trackName: "Se�orita",
                artistName: "Shawn Mendes",
                genre: "canadian pop",
                danceability: 76,
                valence: 75,
                popularity: 79,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                id: uuidv4(),
                trackName: "China",
                artistName: "Anuel AA",
                genre: "reggaeton flow",
                danceability: 79,
                valence: 61,
                popularity: 92,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                id: uuidv4(),
                trackName: "boyfriend (with Social House)",
                artistName: "Ariana Grande",
                genre: "dance pop",
                danceability: 40,
                valence: 70,
                popularity: 85,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                id: uuidv4(),
                trackName: "Beautiful People (feat. Khalid)",
                artistName: "Shawn Mendes",
                genre: "pop",
                danceability: 64,
                valence: 55,
                popularity: 86,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                "id": uuidv4(),
                trackName: "Goodbyes (Feat. Young Thug)",
                artistName: "Post Malone",
                genre: "dfw rap",
                danceability: 58,
                valence: 18,
                popularity: 94,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                id: uuidv4(),
                trackName: "I Don't Care (with Justin Bieber)",
                artistName: "Ed Sheeran",
                genre: "pop",
                danceability: 80,
                valence: 84,
                popularity: 84,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                id: uuidv4(),
                trackName: "Ransom",
                artistName: "Lil Tecca",
                genre: "trap music",
                danceability: 75,
                valence: 23,
                popularity: 92,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                id: uuidv4(),
                trackName: "How Do You Sleep?",
                artistName: "Sam Smith",
                genre: "pop",
                danceability: 48,
                valence: 35,
                popularity: 90,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                id: uuidv4(),
                trackName: "Old Town Road - Remix",
                artistName: "Lil Nas X",
                genre: "country rap",
                danceability: 88,
                valence: 64,
                popularity: 87,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                id: uuidv4(),
                trackName: "bad guy",
                artistName: "Billie Eilish",
                genre: "electropop",
                danceability: 70,
                valence: 56,
                popularity: 95,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                id: uuidv4(),
                trackName: "Callaita",
                artistName: "Bad Bunny",
                genre: "reggaeton",
                danceability: 61,
                valence: 24,
                popularity: 93,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                id: uuidv4(),
                "trackName": "Loco Contigo (feat. J. Balvin & Tyga)",
                artistName: "DJ Snake",
                genre: "dance pop",
                danceability: 82,
                valence: 38,
                popularity: 86,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                id: uuidv4(),
                trackName: "Someone You Loved",
                artistName: "Lewis Capaldi",
                genre: "pop",
                danceability: 50,
                valence: 45,
                popularity: 88,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                id: uuidv4(),
                trackName: "Otro Trago - Remix",
                artistName: "Sech",
                genre: "panamanian pop",
                danceability: 73,
                valence: 76,
                popularity: 87,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                id: uuidv4(),
                trackName: "Money In The Grave (Drake ft. Rick Ross)",
                artistName: "Drake",
                genre: "canadian hip hop",
                danceability: 83,
                valence: 10,
                popularity: 92,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                id: uuidv4(),
                trackName: "No Guidance (feat. Drake)",
                artistName: "Chris Brown",
                genre: "dance pop",
                danceability: 70,
                valence: 14,
                popularity: 82,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                id: uuidv4(),
                trackName: "LA CANCI�N",
                artistName: "J Balvin",
                genre: "latin",
                danceability: 75,
                valence: 43,
                popularity: 90,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                id: uuidv4(),
                trackName: "Sunflower - Spider-Man: Into the Spider-Verse",
                artistName: "Post Malone",
                genre: "dfw rap",
                danceability: 76,
                valence: 91,
                popularity: 91,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                id: uuidv4(),
                trackName: "Lalala",
                artistName: "Y2K",
                genre: "canadian hip hop",
                danceability: 84,
                valence: 50,
                popularity: 88,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                id: uuidv4(),
                trackName: "Truth Hurts",
                artistName: "Lizzo",
                genre: "escape room",
                danceability: 72,
                valence: 41,
                popularity: 91,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                id: uuidv4(),
                trackName: "Piece Of Your Heart",
                artistName: "MEDUZA",
                genre: "pop house",
                danceability: 68,
                valence: 63,
                popularity: 91,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                "id": uuidv4(),
                trackName: "Panini",
                artistName: "Lil Nas X",
                genre: "country rap",
                danceability: 70,
                valence: 48,
                popularity: 91,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                id: uuidv4(),
                trackName: "No Me Conoce - Remix",
                artistName: "Jhay Cortez",
                genre: "reggaeton flow",
                danceability: 81,
                valence: 58,
                popularity: 83,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                id: uuidv4(),
                trackName: "Soltera - Remix",
                artistName: "Lunay",
                genre: "latin",
                danceability: 80,
                valence: 80,
                popularity: 91,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                id: uuidv4(),
                trackName: "bad guy (with Justin Bieber)",
                artistName: "Billie Eilish",
                genre: "electropop",
                danceability: 67,
                valence: 68,
                popularity: 89,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                id: uuidv4(),
                trackName: "If I Can't Have You",
                artistName: "Shawn Mendes",
                genre: "canadian pop",
                danceability: 69,
                valence: 87,
                popularity: 70,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                id: uuidv4(),
                trackName: "Dance Monkey",
                artistName: "Tones and I",
                genre: "australian pop",
                danceability: 82,
                valence: 54,
                popularity: 83,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                id: uuidv4(),
                trackName: "It's You",
                artistName: "Ali Gatie",
                genre: "canadian hip hop",
                danceability: 73,
                valence: 40,
                popularity: 89,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                id: uuidv4(),
                trackName: "Con Calma",
                artistName: "Daddy Yankee",
                genre: "latin",
                danceability: 74,
                valence: 66,
                popularity: 91,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                id: uuidv4(),
                trackName: "QUE PRETENDES",
                artistName: "J Balvin",
                genre: "latin",
                danceability: 64,
                valence: 94,
                popularity: 89,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                id: uuidv4(),
                trackName: "Takeaway",
                artistName: "The Chainsmokers",
                genre: "edm",
                danceability: 29,
                valence: 36,
                popularity: 84,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                id: uuidv4(),
                trackName: "7 rings",
                artistName: "Ariana Grande",
                genre: "dance pop",
                danceability: 78,
                valence: 33,
                popularity: 89,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                id: uuidv4(),
                trackName: "0.958333333",
                artistName: "Maluma",
                genre: "reggaeton",
                danceability: 78,
                valence: 68,
                popularity: 89,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                id: uuidv4(),
                trackName: "The London (feat. J. Cole & Travis Scott)",
                artistName: "Young Thug",
                genre: "atl hip hop",
                danceability: 80,
                valence: 18,
                popularity: 89,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                id: uuidv4(),
                trackName: "Never Really Over",
                artistName: "Katy Perry",
                genre: "dance pop",
                danceability: 77,
                valence: 39,
                popularity: 89,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                id: uuidv4(),
                trackName: "Summer Days (feat. Macklemore & Patrick Stump of Fall Out Boy)",
                artistName: "Martin Garrix",
                genre: "big room",
                danceability: 66,
                valence: 32,
                popularity: 89,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                id: uuidv4(),
                trackName: "Otro Trago",
                artistName: "Sech",
                genre: "panamanian pop",
                danceability: 75,
                valence: 62,
                popularity: 91,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                id: uuidv4(),
                trackName: "Antisocial (with Travis Scott)",
                artistName: "Ed Sheeran",
                genre: "pop",
                danceability: 72,
                valence: 91,
                popularity: 87,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                id: uuidv4(),
                trackName: "Sucker",
                artistName: "Jonas Brothers",
                genre: "boy band",
                danceability: 84,
                valence: 95,
                popularity: 80,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                id: uuidv4(),
                trackName: "fuck, i'm lonely (with Anne-Marie) - from �13 Reasons Why: Season 3�",
                artistName: "Lauv",
                genre: "dance pop",
                danceability: 81,
                valence: 68,
                popularity: 78,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                id: uuidv4(),
                trackName: "Higher Love",
                artistName: "Kygo",
                genre: "edm",
                danceability: 69,
                valence: 40,
                popularity: 88,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                id: uuidv4(),
                trackName: "You Need To Calm Down",
                artistName: "Taylor Swift",
                genre: "dance pop",
                danceability: 77,
                valence: 73,
                popularity: 90,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                id: uuidv4(),
                trackName: "Shallow",
                artistName: "Lady Gaga",
                genre: "dance pop",
                danceability: 57,
                valence: 32,
                popularity: 87,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                id: uuidv4(),
                trackName: "Talk",
                artistName: "Khalid",
                genre: "pop",
                danceability: 90,
                valence: 35,
                popularity: 84,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                id: uuidv4(),
                trackName: "Con Altura",
                artistName: "ROSAL�A",
                genre: "r&b en espanol",
                danceability: 88,
                valence: 75,
                popularity: 88,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                id: uuidv4(),
                trackName: "One Thing Right",
                artistName: "Marshmello",
                genre: "brostep",
                danceability: 66,
                valence: 44,
                popularity: 88,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                id: uuidv4(),
                trackName: "Te Robar�",
                artistName: "Nicky Jam",
                genre: "latin",
                danceability: 67,
                valence: 80,
                popularity: 88,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                id: uuidv4(),
                trackName: "Happier",
                artistName: "Marshmello",
                genre: "brostep",
                danceability: 69,
                valence: 67,
                popularity: 88,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                id: uuidv4(),
                trackName: "Call You Mine",
                artistName: "The Chainsmokers",
                genre: "edm",
                danceability: 59,
                valence: 50,
                popularity: 88,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                id: uuidv4(),
                trackName: "Cross Me (feat. Chance the Rapper & PnB Rock)",
                artistName: "Ed Sheeran",
                genre: "pop",
                danceability: 75,
                valence: 61,
                popularity: 82,
                createdAt: new Date(),
                updatedAt: new Date(),
            }

        ]);
    }
}
